import React from 'react'
import styles from "./journalSingle.module.css"

const WhyWisecticFeature = () =>{
    return(
        <>
            <div className={styles.introductions}>
                <div className={styles.int_contents}>
                    <div className={styles.ab_title}>Introduction</div>
                    <div className={styles.int_text}>I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single stroke at the present moment; and yet I feel that I never was a greater artist than now. When, while the lovely valley teems with vapour around me, and the meridian sun strikes the upper surface of the impenetrable foliage of my trees, and but a few stray gleams steal into the inner sanctuary, I throw myself down among the tall grass by the trickling stream; and, as I lie close to the earth, a thousand unknown plants are noticed by me: when I hear the buzz of the little world among the stalks, and grow familiar with the countless indescribable forms of the insects and flies the Almighty. that I neglect my talents. I should be incapable of drawing a single stroke at the present moment; and yet I feel that </div>
                    <div className={styles.int_text}>I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single stroke at the present moment; and yet I feel that I never was a greater artist than now. When, while the lovely valley teems with vapour around me, and the meridian sun strikes the upper surface of the impenetrable foliage of my trees, and but a few stray gleams steal into the inner sanctuary, I throw myself down among the tall grass by the trickling stream; and, as I lie close to the earth, a thousand unknown plants are noticed by me: when I hear the buzz of the little world among the stalks, and grow familiar with the countless indescribable forms of the insects and flies the Almighty. that I neglect my talents. I should be incapable of drawing a single stroke at the present moment; and yet I feel that </div>
                    <div className={styles.int_image}>
                        <img src="./images/journal/Rectangle 1.png" alt=""/>
                        <div className={styles.int_image_text}><strong>Figure1. </strong>  Figure caption will come here in details</div>
                    </div>
                    <div className={styles.int_text}>I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single stroke at the present moment; and yet I feel that I never was a greater artist than now. When, while the lovely valley teems with vapour around me, and the meridian sun strikes the upper surface of the impenetrable foliage of my trees, and but a few stray gleams steal into the inner sanctuary, I throw myself down among the tall grass by the trickling stream; and, as I lie close to the earth, a thousand unknown plants are noticed by me: when I hear the buzz of the little world among the stalks, and grow familiar with the countless indescribable forms of the insects and flies the Almighty. that I neglect my talents. I should be incapable of drawing a single stroke at the present moment; and yet I feel that </div>
                    <div className={styles.int_text}>I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single stroke at the present moment; and yet I feel that I never was a greater artist than now. When, while the lovely valley teems with vapour around me, and the meridian sun strikes the upper surface of the impenetrable foliage of my trees, and but a few stray gleams steal into the inner sanctuary, I throw myself down among the tall grass by the trickling stream; and, as I lie close to the earth, a thousand unknown plants are noticed by me: when I hear the buzz of the little world among the stalks, and grow familiar with the countless indescribable forms of the insects and flies the Almighty. that I neglect my talents. I should be incapable of drawing a single stroke at the present moment; and yet I feel that </div>
                    <div className={styles.int_text}>I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single stroke at the present moment; and yet I feel that I never was a greater artist than now. When, while the lovely valley teems with vapour around me, and the meridian sun strikes the upper surface of the impenetrable foliage of my trees, and but a few stray gleams steal into the inner sanctuary, I throw myself down among the tall grass by the trickling stream; and, as I lie close to the earth, a thousand unknown plants are noticed by me: when I hear the buzz of the little world among the stalks, and grow familiar with the countless indescribable forms of the insects and flies the Almighty. that I neglect my talents. I should be incapable of drawing a single stroke at the present moment; and yet I feel that </div>
                </div>
            </div>
        </>
    )
}

export default WhyWisecticFeature;
